runtime: go
api_version: go1

skip_files:
- client/

handlers:
- url: /(.*\.(gif|png|jpg|js|css|json))$
  secure: always
  static_files: dist/\1
  upload: dist/.*\.(gif|png|jpg|js|css|json)$

- url: /.*
  secure: always
  script: _go_app

env_variables:
  MSF_USERNAME: "USERNAME"
  MSF_PASSWORD: "PASSWORD"