import { Player } from './player';

export const MOCK_DATA: Player[] = [
    {
        'ID': '10057',
        'LastName': 'Zaitsev',
        'FirstName': 'Nikita',
        'Position': 'D',
        'TeamID': '12',
        'TeamAbbreviation': 'TOR',
        'GamesPlayed': 60,
        'Goals': 5,
        'Assists': 8,
        'Points': 13,
        'PlusMinus': 8
    },
    {
        'ID': '10062',
        'LastName': 'Vesey',
        'FirstName': 'Jimmy',
        'Position': 'LW',
        'TeamID': '9',
        'TeamAbbreviation': 'NYR',
        'GamesPlayed': 79,
        'Goals': 17,
        'Assists': 11,
        'Points': 28,
        'PlusMinus': -18
    },
    {
        'ID': '10064',
        'LastName': 'Lehkonen',
        'FirstName': 'Artturi',
        'Position': 'LW',
        'TeamID': '14',
        'TeamAbbreviation': 'MTL',
        'GamesPlayed': 66,
        'Goals': 12,
        'Assists': 9,
        'Points': 21,
        'PlusMinus': -11
    },
    {
        'ID': '10069',
        'LastName': 'Dvorak',
        'FirstName': 'Christian',
        'Position': 'C',
        'TeamID': '30',
        'TeamAbbreviation': 'ARI',
        'GamesPlayed': 78,
        'Goals': 15,
        'Assists': 22,
        'Points': 37,
        'PlusMinus': -19
    },
    {
        'ID': '10070',
        'LastName': 'Motte',
        'FirstName': 'Tyler',
        'Position': 'C',
        'TeamID': '21',
        'TeamAbbreviation': 'VAN',
        'GamesPlayed': 46,
        'Goals': 5,
        'Assists': 2,
        'Points': 7,
        'PlusMinus': -4
    },
    {
        'ID': '10071',
        'LastName': 'Schmaltz',
        'FirstName': 'Nick',
        'Position': 'C',
        'TeamID': '20',
        'TeamAbbreviation': 'CHI',
        'GamesPlayed': 78,
        'Goals': 21,
        'Assists': 31,
        'Points': 52,
        'PlusMinus': 1
    },
    {
        'ID': '10072',
        'LastName': 'Forsling',
        'FirstName': 'Gustav',
        'Position': 'D',
        'TeamID': '20',
        'TeamAbbreviation': 'CHI',
        'GamesPlayed': 41,
        'Goals': 3,
        'Assists': 10,
        'Points': 13,
        'PlusMinus': -2
    },
    {
        'ID': '10073',
        'LastName': 'Kempny',
        'FirstName': 'Michal',
        'Position': 'D',
        'TeamID': '5',
        'TeamAbbreviation': 'WSH',
        'GamesPlayed': 53,
        'Goals': 3,
        'Assists': 7,
        'Points': 10,
        'PlusMinus': 14
    },
    {
        'ID': '10074',
        'LastName': 'Dell',
        'FirstName': 'Aaron',
        'Position': 'G',
        'TeamID': '26',
        'TeamAbbreviation': 'SJS',
        'GamesPlayed': 31,
        'Goals': 0,
        'Assists': 1,
        'Points': 1,
        'PlusMinus': 0
    },
    {
        'ID': '10075',
        'LastName': 'Buchnevich',
        'FirstName': 'Pavel',
        'Position': 'LW',
        'TeamID': '9',
        'TeamAbbreviation': 'NYR',
        'GamesPlayed': 74,
        'Goals': 14,
        'Assists': 29,
        'Points': 43,
        'PlusMinus': -3
    },
    {
        'ID': '10076',
        'LastName': 'Heinen',
        'FirstName': 'Danton',
        'Position': 'C',
        'TeamID': '11',
        'TeamAbbreviation': 'BOS',
        'GamesPlayed': 76,
        'Goals': 16,
        'Assists': 31,
        'Points': 47,
        'PlusMinus': 10
    },
    {
        'ID': '10077',
        'LastName': 'Czarnik',
        'FirstName': 'Austin',
        'Position': 'C',
        'TeamID': '11',
        'TeamAbbreviation': 'BOS',
        'GamesPlayed': 10,
        'Goals': 0,
        'Assists': 4,
        'Points': 4,
        'PlusMinus': -1
    }
];
